### ISSUE TITLE
bigjq@0.0.15 error

### ISSUE THREAD

**Issue by HansGabriel** [interplanaria/npd#1]
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! bigjq@0.0.15 postinstall: `./run.sh`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the bigjq@0.0.15 postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Lenovo\AppData\Roaming\npm-cache\_logs\2019-12-18T08_15_46_248Z-debug.log

**Comment by JorgeRobins** [comment]
Hi @HansGabriel,

I believe the issue is that you are trying to run a .sh in a shell that doesn't support it e.g. Visual Studio Code defaults to Powershell.

You can add git bash with a command like:

`npm config set script-shell "C:\\Program Files\\git\\bin\\bash.exe"`

Then you can try and install the package again and the post install .sh for the bigjq dependency should work.

Jorge
